apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubernetes-config-app
  namespace: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: express

  template:
    metadata:
      labels:
        app: express

    spec:
      containers:
        - name: express-container
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Kubernetes"

          ports:
            - containerPort: 5678
    
          envFrom:
            - configMapRef:
                name: express-config

            - secretRef:
                name: express-secret
