apiVersion: v1
kind: Service

metadata:
  name: express-service
  namespace: dev

spec:

  selector:
    app: express

  type: NodePort

  ports:

    - port: 5678

      targetPort: 5678

      nodePort: 30080
